# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from mars_robot_msgs/sensor_msg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class sensor_msg(genpy.Message):
  _md5sum = "ce384a3455ea54b3bf3d0b088d180fe5"
  _type = "mars_robot_msgs/sensor_msg"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint16 auger_depth
float32 auger_accel_z
float32 auger_accel_x
"""
  __slots__ = ['auger_depth','auger_accel_z','auger_accel_x']
  _slot_types = ['uint16','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       auger_depth,auger_accel_z,auger_accel_x

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(sensor_msg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.auger_depth is None:
        self.auger_depth = 0
      if self.auger_accel_z is None:
        self.auger_accel_z = 0.
      if self.auger_accel_x is None:
        self.auger_accel_x = 0.
    else:
      self.auger_depth = 0
      self.auger_accel_z = 0.
      self.auger_accel_x = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_H2f().pack(_x.auger_depth, _x.auger_accel_z, _x.auger_accel_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.auger_depth, _x.auger_accel_z, _x.auger_accel_x,) = _get_struct_H2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_H2f().pack(_x.auger_depth, _x.auger_accel_z, _x.auger_accel_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.auger_depth, _x.auger_accel_z, _x.auger_accel_x,) = _get_struct_H2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_H2f = None
def _get_struct_H2f():
    global _struct_H2f
    if _struct_H2f is None:
        _struct_H2f = struct.Struct("<H2f")
    return _struct_H2f
